### ISSUE TITLE
feature request: skip validation for existing indices

### ISSUE THREAD

**Issue by yokomotod** [po3rin/eskeeper#12]
eskeeper will do nothing if the index in yaml already exists, but now eskeeper will validate all indices in yaml.

it takes longer time so i would like to skip it.

**Comment by yokomotod** [comment]
do you think it's ok to skip always, or should be with option flag ?

**Comment by po3rin** [comment]
I think it's okay to always skip the validation of an existing index

**Comment by po3rin** [comment]
I will deal with this PR.
https://github.com/po3rin/eskeeper/pull/13
